### ISSUE TITLE
Ubuntu and Rails - LoadError: Could not open library 'vips'

### ISSUE THREAD

**Issue by blackpond** [libvips/ruby-vips#203]
Ubuntu 16.04.3 LTS
Rails 5.2.3
Ruby 2.4

Gemfile: have 

I'm having issues deploy to my production server.  I've gone through the issues others have had with Ubuntu and haven't found a fix yet.  Any help pointing me in the right direction would be appreciated, I just moved everything from using Magick, and it's 3X faster!

```
rake stdout: rake aborted!
LoadError: Could not open library 'vips': vips: cannot open shared object file: No such file or directory.
Could not open library 'libvips.so': libvips.so: cannot open shared object file: No such file or directory
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/ffi-1.11.1/lib/ffi/library.rb:145:in `block in ffi_lib'
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `map'
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `ffi_lib'
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/ruby-vips-2.0.14/lib/vips.rb:471:in `<module:Vips>'
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/ruby-vips-2.0.14/lib/vips.rb:462:in `<top (required)>'
/home/deploy/dispatch/releases/20190826065835/config/application.rb:7:in `require'
/home/deploy/dispatch/releases/20190826065835/config/application.rb:7:in `<top (required)>'
/home/deploy/dispatch/releases/20190826065835/Rakefile:4:in `require'
/home/deploy/dispatch/releases/20190826065835/Rakefile:4:in `<top (required)>'
/home/deploy/dispatch/shared/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `load'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:335:in `exec'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/home/deploy/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/home/deploy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
rake stderr: Nothing written
```

Vips seems to be working on the Server:
`2.4.1 :004 > require 'vips'`
` => true `

`2.4.1 :005 > Vips::Image`
 `=> Vips::Image `

`$ vips -v`
`vips-8.9.0-Mon Aug 26 05:12:22 UTC 2019`
`$ which vips`
`/usr/local/bin/vips`

bash_profile:
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/X11/lib/pkgconfig`

bashrc:
`export PATH="$PATH:$HOME/.rvm/bin"
export VIPSHOME=/usr/local
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib
export PATH=$PATH:$VIPSHOME/bin
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$VIPSHOME/lib/pkgconfig
export MANPATH=$MANPATH:$VIPSHOME/man
export PYTHONPATH=$VIPSHOME/lib/python2.7/site-packages`

**Comment by jcupitt** [comment]
Hello, I think (from memory) it loads libraries from `LD_CONFIG_PATH`. Has that env var been lost somehow before the server process sees it?

You could perhaps also add `/usrlocal/lib` to your `ld.so.conf`, it might be safer.

**Comment by jcupitt** [comment]
Oh heh no problem, I'm glad it's working.
