### ISSUE TITLE
g_value_set_enum no implicit conversion of true into Integer in Vips::Image.thumbnail

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#224]
Trying to use vips to make thumbnails (the goal is `[width, height].min=100` keeping aspect ratio and then crop to 100x100). But got this error:
```ruby
src = "src_src/daily/qwe_qwe123_1280.jpg"
dst = "website/preview/2010-9-7.jpg"
Vips::Image.thumbnail(src, 100, height: 100, crop: true).write_to_file dst
```
```none
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/gvalue.rb:155:in `g_value_set_enum': no implicit conversion of true into Integer (TypeError)
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/gvalue.rb:155:in `set'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/object.rb:258:in `set'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:249:in `set'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:398:in `block in call'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:388:in `each'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:388:in `call'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.17/lib/vips/image.rb:216:in `method_missing'
```

**Comment by Nakilon** [comment]
Oh I'm stupid. It's my `true`. Didn't read the `crop` docs. You can delete this.
