### ISSUE TITLE
Wget required

### ISSUE THREAD

**Issue by semaperepelitsa** [libvips/ruby-vips#374]
When trying to install this gem on macOS 14.0 I got this error:

> Command failed with status (127): [wget https://github.com/libvips/libvips/re...]

It got resolved after `brew install wget`

Would be helpful to mention that in the readme.

<details>

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching ffi 1.16.3
Installing ffi 1.16.3 with native extensions
Fetching vips 8.12.2
Installing vips 8.12.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sema/.gem/ruby/3.2.0/gems/vips-8.12.2/ext
/Users/sema/.rubies/ruby-3.2.2/bin/ruby -rrubygems /Users/sema/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake
RUBYARCHDIR\=/Users/sema/.gem/ruby/3.2.0/extensions/arm64-darwin-23/3.2.0-static/vips-8.12.2
RUBYLIBDIR\=/Users/sema/.gem/ruby/3.2.0/extensions/arm64-darwin-23/3.2.0-static/vips-8.12.2
wget https://github.com/libvips/libvips/releases/download/v8.12.2/vips-8.12.2.tar.gz -O vips-8.12.2.tar.gz
rake aborted!
Command failed with status (127): [wget https://github.com/libvips/libvips/re...]
/Users/sema/.gem/ruby/3.2.0/gems/vips-8.12.2/ext/Rakefile:13:in `block in <top (required)>'
Tasks: TOP => default => fetch
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/sema/.gem/ruby/3.2.0/gems/vips-8.12.2 for inspection.
Results logged to /Users/sema/.gem/ruby/3.2.0/extensions/arm64-darwin-23/3.2.0-static/vips-8.12.2/gem_make.out

  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:120:in `run'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/rake_builder.rb:30:in `build'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:188:in `build_extension'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:222:in `block in build_extensions'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `each'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `build_extensions'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:203:in `install'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer/parallel_installer.rb:130:in `do_install'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer/parallel_installer.rb:121:in `block in worker_pool'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /Users/sema/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing vips (8.12.2), and Bundler cannot continue.

In Gemfile:
  vips
```

</details>

**Comment by semaperepelitsa** [comment]
Nevermind - I was installing the wrong gem, should be `ruby-vips`.
