### ISSUE TITLE
relational_const: vector must have 1 or 3 elements (Vips::Error)

### ISSUE THREAD

**Issue by noraj** [libvips/ruby-vips#391]
**Describe the bug**

I saw the script [here](https://github.com/libvips/libvips/issues/872#issuecomment-744900174) to match and replace a color and wanted to use it.

```ruby
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

old_colour = [0, 223, 255, 255]

new_colour = [226, 211, 80, 255]

image = (image == old_colour).bandand.ifthenelse(new_colour, image)

image.write_to_file ARGV[1]
```

But I have this error:

```
➜ ruby test.rb test3.png test.png

(process:62779): VIPS-WARNING **: 17:17:56.930: unable to load "/usr/lib/vips-modules-8.15/vips-openslide.so" -- libopenslide.so.1: cannot open shared object file: No such file or directory
/home/noraj/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-vips-2.2.1/lib/vips/operation.rb:228:in `build': relational_const: vector must have 1 or 3 elements (Vips::Error)
        from /home/noraj/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-vips-2.2.1/lib/vips/operation.rb:481:in `call'
        from /home/noraj/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-vips-2.2.1/lib/vips/image.rb:160:in `call_enum'
        from /home/noraj/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-vips-2.2.1/lib/vips/image.rb:1166:in `=='
        from test.rb:9:in `<main>'
```

The warning with `libopenslide` has nothing to do with the problem. The issue is the error: `relational_const: vector must have 1 or 3 elements (Vips::Error)`.

It seems to happen with any image exported to PNG from [photopea](https://www.photopea.com/).

The image is like that:

```
➜ exiftool test3.png                                        
ExifTool Version Number         : 12.76
File Name                       : test3.png
Directory                       : .
File Size                       : 25 kB
File Modification Date/Time     : 2024:03:09 17:17:53+01:00
File Access Date/Time           : 2024:03:09 17:17:56+01:00
File Inode Change Date/Time     : 2024:03:09 17:17:53+01:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 1280
Image Height                    : 720
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
SRGB Rendering                  : Relative Colorimetric
Pixels Per Unit X               : 2835
Pixels Per Unit Y               : 2835
Pixel Units                     : meters
Image Size                      : 1280x720
Megapixels                      : 0.922
```

You can get the example image here:

![test3](https://github.com/libvips/ruby-vips/assets/16578570/5f3c7da2-945f-4c04-bd14-1b7fe1fbf181)

However, I saw that with another random image I took from my PC that was not generated with photopea, that the error is not happening.

```
➜ ruby test.rb ~/Pictures/icons8-bug-96.png test.png            

(process:65265): VIPS-WARNING **: 17:23:00.497: unable to load "/usr/lib/vips-modules-8.15/vips-openslide.so" -- libopenslide.so.1: cannot open shared object file: No such file or directory
```

```
➜ exiftool ~/Pictures/icons8-bug-96.png            
ExifTool Version Number         : 12.76
File Name                       : icons8-bug-96.png
Directory                       : /home/noraj/Pictures
File Size                       : 2.5 kB
File Modification Date/Time     : 2019:07:20 14:51:27+02:00
File Access Date/Time           : 2024:03:09 00:47:45+01:00
File Inode Change Date/Time     : 2020:01:12 18:08:03+01:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 96
Image Height                    : 96
Bit Depth                       : 8
Color Type                      : Palette
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Palette                         : (Binary data 768 bytes, use -b option to extract)
Transparency                    : (Binary data 180 bytes, use -b option to extract)
Image Size                      : 96x96
Megapixels                      : 0.009
```

The difference I see is Color Type Palette vs RGB.

**To Reproduce**

1. Ruby script in example above
2. Image test3.png above
3. `ruby test.rb test3.png test.png `

**Expected behavior**

Process the image without error

**Screenshots**

N/A

**Additional context**

- OS: ArchLinux

```
➜ pacman -Qi libvips | grep Version
Version         : 8.15.1-5

➜ gem info ruby-vips | grep -oE '\(.+\)'  
(2.2.1)

➜ ruby --version                                                              
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

**Comment by jcupitt** [comment]
Hello @noraj,

This isn't a bug -- if you use a vector as a pixel constant, it must either have 1 element, or the number of bands in the image. If you pass a 1 element vector, libvips will internally copy it N times to make an N element vector.

For example:

```
$ vipsheader k2.jpg
k2.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
$ vips linear k2.jpg x.v "1 2 3" 4
$ vips linear k2.jpg x.v "1 2 3 4" 1
linear: vector must have 1 or 3 elements
$
```

PNGs can have 1, 2, 3 or 4 bands, depending on the kind of PNG, so you need to check before building the vector, or force the PNG to the type you want (RGBA in this case I guess). Even more confusingly, the maximum value (ie. solid in the alpha) can be 255 or 65535, depending on whether your PNG is 8 or 16 bits.

A simple fix might be eg.

```ruby
image = .... an image from somewhere
# transform to 0-255 RGB, possibly with extra alpha bands
image = image.colourspace :srgb
# add an alpha if there is none
image = image.add_alpha if not image.has_alpha?
# there might be more than 4 bands (images can have many alpha channels), just 
# take the first so we are guaranteed RGBA
image = image[0..3]
# now we can safely test against a fixed length vector
image = (image == [1, 2, 3, 255]).bandand.ifthenelse([4, 5, 6, 255], image)
```

**Comment by jcupitt** [comment]
A better solution would probably be to have something representing a colour and a colourspace, force the image to that, and then make the mask.

```ruby
old_colour = ["srgb", [1, 2, 3]]
# compute a mask of matching pixels
image = ... something
mask = (image.colourspace(old_colour[0])[0..old_colour[1].length] == old_colour[1]).bandand
# now use eg. ifthenelse to change the pixels in image
```

You'd need something to turn the rgb colour space into something that matches image's colourspace (eg. what if it's cmyk).

**Comment by noraj** [comment]
@jcupitt Thanks for the explanation. Image processing is indeed complex.
